-- Начальные данные справочника стран (ISO 3166-1 alpha-2 / alpha-3).
-- Повторный запуск миграции безопасен: конфликты по уникальным кодам игнорируются.
INSERT INTO person.countries (name, alpha2, alpha3, status)
VALUES ('Russia', 'RU', 'RUS', 'ACTIVE'),
       ('United States', 'US', 'USA', 'ACTIVE'),
       ('Germany', 'DE', 'DEU', 'ACTIVE'),
       ('France', 'FR', 'FRA', 'ACTIVE'),
       ('United Kingdom', 'GB', 'GBR', 'ACTIVE'),
       ('Italy', 'IT', 'ITA', 'ACTIVE'),
       ('Spain', 'ES', 'ESP', 'ACTIVE'),
       ('Netherlands', 'NL', 'NLD', 'ACTIVE'),
       ('Poland', 'PL', 'POL', 'ACTIVE'),
       ('Switzerland', 'CH', 'CHE', 'ACTIVE'),
       ('Sweden', 'SE', 'SWE', 'ACTIVE'),
       ('Finland', 'FI', 'FIN', 'ACTIVE'),
       ('Norway', 'NO', 'NOR', 'ACTIVE'),
       ('Czechia', 'CZ', 'CZE', 'ACTIVE'),
       ('Serbia', 'RS', 'SRB', 'ACTIVE'),
       ('Turkey', 'TR', 'TUR', 'ACTIVE'),
       ('China', 'CN', 'CHN', 'ACTIVE'),
       ('Japan', 'JP', 'JPN', 'ACTIVE'),
       ('South Korea', 'KR', 'KOR', 'ACTIVE'),
       ('India', 'IN', 'IND', 'ACTIVE'),
       ('Brazil', 'BR', 'BRA', 'ACTIVE'),
       ('Canada', 'CA', 'CAN', 'ACTIVE'),
       ('Australia', 'AU', 'AUS', 'ACTIVE'),
       ('Israel', 'IL', 'ISR', 'ACTIVE'),
       ('United Arab Emirates', 'AE', 'ARE', 'ACTIVE'),
       ('Kazakhstan', 'KZ', 'KAZ', 'ACTIVE'),
       ('Belarus', 'BY', 'BLR', 'ACTIVE'),
       ('Ukraine', 'UA', 'UKR', 'ACTIVE'),
       ('Uzbekistan', 'UZ', 'UZB', 'ACTIVE'),
       ('Kyrgyzstan', 'KG', 'KGZ', 'ACTIVE'),
       ('Tajikistan', 'TJ', 'TJK', 'ACTIVE'),
       ('Armenia', 'AM', 'ARM', 'ACTIVE'),
       ('Georgia', 'GE', 'GEO', 'ACTIVE'),
       ('Azerbaijan', 'AZ', 'AZE', 'ACTIVE'),
       ('Moldova', 'MD', 'MDA', 'ACTIVE')
ON CONFLICT DO NOTHING;
