server:
  port: 8091

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:individual}
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:individual}/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0


otel:
  exporter:
    otlp:
      endpoint: ${OTLP_EXPORTER_ENDPOINT:http://localhost:4318}
      protocol: http/protobuf
  logs:
    exporter: none
  metrics:
    exporter: none
logging:
  config: "classpath:logback.xml"

keycloak:
  client-id: ${KEYCLOAK_CLIENT_ID:individuals-api}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:lBO6Dz0IJXoNxqfZNPhf4qGxFB0HytaV}
  realm: ${KEYCLOAK_REALM:individual}


person-service:
  base-url: ${PERSONS_SERVICE_URL:http://localhost:8092}

springdoc:
  swagger-ui:
    url: /api-docs
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  api-docs:
    path: /api-docs
    enabled: true